extends: default_config.yaml

scene_name: D03_bunny_light_right

input:
  file_path: './data/D03_bunny_light_right/D03_bunny_light_right.npz.zst'
  end_idx: 1152

output:
  file_path: './output/D03_bunny_light_right/denoised_video.h5'
  cache_dir: './output/D03_bunny_light_right/cache'

temporal_transform:
  num_levels: 6
