extends: default_config.yaml

scene_name: D08_book_colorchart_L5

input:
  file_path: './data/D08_book_colorchart_L5/D08_book_colorchart_L5.npz.zst'
  end_idx: 1152

output:
  file_path: './output/D08_book_colorchart_L5/denoised_video.h5'
  cache_dir: './output/D08_book_colorchart_L5/cache'

temporal_transform:
  num_levels: 6
