extends: default_config.yaml

scene_name: D08_book_colorchart_L4

input:
  file_path: './data/D08_book_colorchart_L4/D08_book_colorchart_L4.npz.zst'
  end_idx: 1152

output:
  file_path: './output/D08_book_colorchart_L4/denoised_video.h5'
  cache_dir: './output/D08_book_colorchart_L4/cache'

temporal_transform:
  num_levels: 6
