extends: default_config.yaml

scene_name: D09_cardboard_fan_L4

input:
  file_path: './data/D09_cardboard_fan_L4/D09_cardboard_fan_L4.npz.zst'
  end_idx: 1152

output:
  file_path: './output/D09_cardboard_fan_L4/denoised_video.h5'
  cache_dir: './output/D09_cardboard_fan_L4/cache'

temporal_transform:
  num_levels: 6
